=== sitexa/jbrx/tools/src/main/resources/trans/DBBus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ServicePlugin">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Value" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ServiceConfig" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="TransService" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="ClassPath" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="MongoService" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="Resource" type="xs:string" use="required"/>
									<xs:attribute name="Encoding" type="xs:string" use="optional" default="utf-8"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DataService" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="Resource" type="xs:string" use="required"/>
									<xs:attribute name="Encoding" type="xs:string" use="optional" default="utf-8"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Name" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="(_|[a-z]|[A-Z])(_|[a-z]|[A-Z]|[0-9])*"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DBBus">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Value" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="DataServiceEngine" type="xs:string" default="" minOccurs="0"/>
				<xs:element name="DataGroup" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Database" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="User">
											<xs:complexType>
												<xs:attribute name="UserName" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="Password" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="Name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="Value" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="ConnectionPool" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="MinConnectionCount" type="xs:int" default="1" minOccurs="0"/>
													<xs:element name="MaxConnectionCount" type="xs:int" default="3" minOccurs="0"/>
													<xs:element name="Timeout" type="xs:int" default="60" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="URI" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="LoadLevel" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:int">
												<xs:minInclusive value="1"/>
												<xs:maxInclusive value="100"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="KeyIV" type="xs:string" use="optional" default=""/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="((_|[a-z]|[A-Z])(_|[a-z]|[A-Z]|[0-9])*)*#?"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Driver" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ClassPath" type="xs:string" use="required"/>
						<xs:attribute name="InstanceCount" type="xs:int" use="optional" default="0"/>
						<xs:attribute name="SubDatabaseCount" type="xs:unsignedInt" use="optional" default="0"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="MongoDB" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="DB" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="((_|[a-z]|[A-Z])(_|[a-z]|[A-Z]|[0-9])*)*#?"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="URI" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="UserName" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Password" type="xs:string" use="required"/>
									<xs:attribute name="KeyIV" type="xs:string" use="optional" default=""/>
									<xs:attribute name="ReadReference" use="optional" default="PRIMARY">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="PRIMARY"/>
												<xs:enumeration value="PRIMARY-PREFERRED"/>
												<xs:enumeration value="SECONDARY"/>
												<xs:enumeration value="SECONDARY-PREFERRED"/>
												<xs:enumeration value="NEAREST"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ConnectionCount" type="xs:int" use="optional" default="20"/>
									<xs:attribute name="KeepAlive" type="xs:boolean" use="optional" default="true"/>
									<xs:attribute name="Timeout" type="xs:int" use="optional" default="999999999"/>
									<xs:attribute name="AuthMechanism" use="optional" default="">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value=""/>
												<xs:enumeration value="GSSAPI"/>
												<xs:enumeration value="MongoCR"/>
												<xs:enumeration value="MongoX509"/>
												<xs:enumeration value="Plain"/>
												<xs:enumeration value="ScramSha1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="SubDBCount" use="optional" default="0">
										<xs:simpleType>
											<xs:restriction base="xs:unsignedInt">
												<xs:pattern value="([0-9]{1,9})|(\{(_|_|[a-z]|[A-Z])(_|_|[a-z]|[A-Z]|[0-9]|\.|\[|\])*\})"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="DefaultDBId" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="((_|[a-z]|[A-Z])(_|[a-z]|[A-Z]|[0-9])*)*"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Plugin" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Resource" type="xs:string" use="required"/>
						<xs:attribute name="Encoding" type="xs:string" use="optional" default="utf-8"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="BigTableGroup" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="Resource" type="xs:string" use="required"/>
						<xs:attribute name="Encoding" type="xs:string" use="optional" default="utf-8"/>
					</xs:complexType>
				</xs:element>				
			</xs:sequence>
			<xs:attribute name="DataGroupId" use="optional" default="">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="((_|[a-z]|[A-Z])(_|[a-z]|[A-Z]|[0-9])*)*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sitexa/jbrx/service/src/main/resources/dbbus_dev.xml
<?xml version="1.0" encoding="utf-8"?>
<DBBus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="trans/DBBus.xsd" DataGroupId="jbrx">
	
	<DataServiceEngine>com.gavin.plugin.database.BigDataEngine</DataServiceEngine>
	<!-- mysql连接的依赖包是高版本的情况下 -->
	<!-- jdbc:mysql://readUser.www.mysql:8084/www?Unicode=true&amp;characterEncoding=utf8 -->
	<DataGroup Id="readUser" ClassPath="com.gavin.plugin.database.DataEngine" Driver="com.cj.mysql.jdbc.Driver">
		<Database URI="jdbc:mysql://read.www.rxgj.mysql:3306/jbrx?useUnicode=true&amp;characterEncoding=utf8&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=Hongkong&amp;useSSL=false" LoadLevel="100" KeyIV="DECSECURITYKEYABCDEFG|EiJPWIgQQDgoJXlRy91SZncpdZgwQEHi">
			<User UserName="root" Password="123456"/>
			<ConnectionPool>
				<MinConnectionCount>1</MinConnectionCount>
				<MaxConnectionCount>5</MaxConnectionCount>
			</ConnectionPool>
		</Database>
	</DataGroup>
	
	<DataGroup Id="writeUser" ClassPath="com.gavin.plugin.database.DataEngine" Driver="com.cj.mysql.jdbc.Driver">
		<Database URI="jdbc:mysql://write.www.rxgj.mysql:3306/jbrx?useUnicode=true&amp;characterEncoding=utf8&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=Hongkong&amp;useSSL=false" LoadLevel="100" KeyIV="DECSECURITYKEYABCDEFG|EiJPWIgQQDgoJXlRy91SZncpdZgwQEHi">
			<User UserName="root" Password="123456"/>
			<ConnectionPool>
				<MinConnectionCount>1</MinConnectionCount>
				<MaxConnectionCount>5</MaxConnectionCount>
			</ConnectionPool>
		</Database>
	</DataGroup>
	<Plugin Resource="trans/service/plugin.xml" Encoding="utf-8"/>
	
 </DBBus>

=== sitexa/jbrx/tools/src/main/resources/dbbus_pro.xml
<?xml version="1.0" encoding="UTF-8" ?>
<DBBus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="trans/DBBus.xsd" DataGroupId="jbrx">

    <DataServiceEngine>com.gavin.plugin.database.BigDataEngine</DataServiceEngine>

    <DataGroup Id="readTable" Driver="com.mysql.cj.jdbc.Driver" ClassPath="com.gavin.plugin.database.DataEngine">
        <Database URI="jdbc:mysql://read.www.rxgj.mysql:3306/jbrx?useUnicode=true&amp;characterEncode=utf8&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=Hongkong&amp;useSSL=false" LoadLevel="100">
            <User UserName="root" Password="root"/>
            <ConnectionPool>
                <MinConnectionCount>1</MinConnectionCount>
                <MaxConnectionCount>5</MaxConnectionCount>
            </ConnectionPool>
        </Database>
    </DataGroup>

    <DataGroup Id="writeTable" Driver="com.mysql.cj.jdbc.Driver" ClassPath="com.gavin.plugin.database.DataEngine">
        <Database URI="jdbc:mysql://read.www.rxgj.mysql:3306/jbrx?useUnicode=true&amp;characterEncode=utf8&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=Hongkong&amp;useSSL=false" LoadLevel="100">
            <User UserName="root" Password="root"/>
            <ConnectionPool>
                <MinConnectionCount>1</MinConnectionCount>
                <MaxConnectionCount>5</MaxConnectionCount>
            </ConnectionPool>
        </Database>
    </DataGroup>
    <Plugin Resource="trans/table/plugin.xml" Encoding="utf-8"/>

</DBBus>

=== sitexa/jbrx/msg-service/src/main/resources/dbbus_dev.xml
<?xml version="1.0" encoding="utf-8"?>
<DBBus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="trans/DBBus.xsd" DataGroupId="jbrx">
	
	<DataServiceEngine>com.gavin.plugin.database.BigDataEngine</DataServiceEngine>

	<DataGroup Id="readMessage" ClassPath="com.gavin.plugin.database.DataEngine" Driver="com.mysql.jdbc.Driver">
		<Database URI="jdbc:mysql://readMessage.www.mall.mysql:3306/jbrx?useUnicode=true&amp;characterEncoding=utf8&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=Hongkong&amp;useSSL=false" LoadLevel="100" KeyIV="DECSECURITYKEYABCDEFG|EiJPWIgQQDgoJXlRy91SZncpdZgwQEHi">
			<User UserName="root" Password="root"/>
			<ConnectionPool>
				<MinConnectionCount>1</MinConnectionCount>
				<MaxConnectionCount>2</MaxConnectionCount>
			</ConnectionPool>
		</Database>
	</DataGroup>
	
	<DataGroup Id="writeMessage" ClassPath="com.gavin.plugin.database.DataEngine" Driver="com.mysql.jdbc.Driver">
		<Database URI="jdbc:mysql://writeMessage.www.mall.mysql:3306/jbrx?useUnicode=true&amp;characterEncoding=utf8&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=Hongkong&amp;useSSL=false" LoadLevel="100" KeyIV="DECSECURITYKEYABCDEFG|EiJPWIgQQDgoJXlRy91SZncpdZgwQEHi">
			<User UserName="root" Password="root"/>
			<ConnectionPool>
				<MinConnectionCount>1</MinConnectionCount>
				<MaxConnectionCount>2</MaxConnectionCount>
			</ConnectionPool>
		</Database>
	</DataGroup>

	<Plugin Resource="trans/message/plugin.xml" Encoding="utf-8"/>			
	
</DBBus>
